--- 
title: "KUKY Report"
author: "Silvie Cinková"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
#bibliography: [book.bib, packages.bib]
rmd_files: [
#"index.Rmd",
"01_guide_to_data_files.Rmd",
"02_data_preparation.Rmd",
"03_network_preprocessing01.Rmd",
"04_network_preprocessing02.Rmd"
]
biblio-style: apalike
link-citations: yes
github-repo: cinkova/kuky-explore01/
description: "These are my notes to the KUKY corpus as I was exploring it and experimenting with it. Based on the minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---



```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

```{r include=FALSE}
#Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.
#To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>.
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


  